const obj = {
  watches: [
    {
      id: 0,
      title: "men watches",
      img: "./Images/watch.jpeg",
      cat: "Watches",
      price: "50 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 1,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch01.jpeg",
      price: "50 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 2,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch02.jpeg",
      price: "50 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 3,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch03.jpeg",
      price: "500 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 4,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch04.jpeg",
      price: "200 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 5,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch06.jpeg",
      price: "300 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 6,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch06.jpeg",
      price: "400 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 7,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch07.webp",
      price: "800 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 8,
      title: "men watches",
      img: "./Images/watch08.webp",
      cat: "Watches",
      price: "5000 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 9,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch09.webp",
      price: "590 $",
      discription: "Black and White Stainless Steel",
    },
    {
      id: 10,
      title: "men watches",
      cat: "Watches",
      img: "./Images/watch10.webp",
      price: "1000 $",
      discription: "Black and White Stainless Steel",
    },
  ],
  Fashion: [
    {
      id: 0,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress.jpeg",
      price: "400 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 2,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress01.jpeg",
      price: "1000 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 3,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress02.jpeg",
      price: "4000 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 4,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress10.jpeg",
      price: "9000 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 5,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress.jpeg",
      price: "7500 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 6,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress05.jpeg",
      price: "4600 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 7,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress06.jpeg",
      price: "2000 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 8,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress07.jpeg",
      price: "4250 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 9,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress08.jpeg",
      price: "9000 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 10,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress9.jpeg",
      price: "3900 $",
      discription: "Skill Dress By Alkaram Studio",
    },
    {
      id: 11,
      title: "Fashion",
      cat: "Fashion",
      img: "./Images/Fashion/dress10.jpeg",
      price: "8090 $",
      discription: "Skill Dress By Alkaram Studio",
    },
  ],
};
export default obj;
